---
title: "R Notebook"
output: html_notebook
---

1. Conociendo los datos

1.1

```{r}
library(tidyverse)
```

1.2

```{r}
yearly <- read_csv("deaths_handwashing.csv") 
```
1.3

```{r}
yearly
```

2. El alarmante número de muertes

2.1

```{r}
yearly <- yearly %>%
  mutate(proportion_deaths = deaths / births)
```

2.2
```{r}
yearly
```

3. Muertes en las clínicas

3.1 y 3.2

```{r}
yearly %>%
  group_by(clinic) %>%
  ggplot(aes(x= year, y=proportion_deaths, color=clinic)) +
  geom_line()

```



4. Comienza el lavado de manos

4.1
```{r}
monthly <- read_csv("deaths_clinic_1.csv")
monthly
```



4.2

```{r}
monthly <- monthly %>%
  mutate( proportion_deaths = deaths/births )
```

4.3

```{r}
head(monthly)
```



5. El efecto del lavado de manos

5.1 y 5.2

```{r}
ggplot(monthly, aes(x=date, y=proportion_deaths)) +
  geom_line() +
  labs( x = "Date", y = "Proportion of deaths", title="Proportion of deaths vs. Dates")
```


6.1 

```{r}

monthly <- monthly %>%
  mutate(handwashing_started = if_else(as.Date("1846-12-31") < date, TRUE, FALSE ))
monthly
```

6.2 y 6.3

```{r}
ggplot(monthly, aes(x=date, y=proportion_deaths, color=handwashing_started)) +
  geom_line() +
  labs( x = "Date", y = "Proportion of deaths", title="Proportion of deaths vs. Dates")
```

7.1 y 7.2

```{r}

month_summary <- monthly %>%
  group_by(handwashing_started) %>%
  summarize(mean_proportion_deaths = mean(proportion_deaths))
month_summary
```


7.3

```{r}
month_summary
```











